import {
  faceit,
  insure,
  loopStudio,
  manage,
  myHome,
  eyeCam,
  shortly,
  airFilter,
  photoSnapshot,
  account,
} from "../images/svg-icons/export";
const data = [
  {
    position: "Senior Frontend Developer",
    business: "Faceit",
    time: ["new", "featured"],
    logo: faceit,
    id_class: ["frontend", "senior", "HTML", "javascript", "css"],
    features: ["1d ago", "full time", "USA only"],
  },

  {
    position: "Fullstack Developer",
    business: "Insure",
    time: ["new", "featured"],
    logo: insure,
    id_class: ["fullstack", "midweight", "python", "react"],
    features: ["1d ago", "part time", "remote"],
  },

  {
    position: "Junior Frontend Developer",
    business: "LoopStudio",
    time: ["new"],
    logo: loopStudio,
    id_class: ["frontend", "junior", "react", "sass", "javascript"],
    features: ["2d ago", "part time", "USA only"],
  },
  {
    position: "Junior Frontend Developer",
    business: "Manage.ent",
    time: "",
    logo: manage,
    id_class: ["frontend", "junior", "tailwind", "angular",'HTML'],
    features: ["1w ago", "full time", "UK only"],
  },
  {
    position: "Software Engineer",
    business: "myHome.inc",
    time: ["new"],
    logo: myHome,
    id_class: ["ruby", "fullstack", "python", "javascript",'HTML'],
    features: ["2w ago", "Full Time", "Woldwide"],
  },
  {
    position: "Test QA Jr",
    business: "EyeCam",
    time: "",
    logo: eyeCam,
    id_class: ["node", "python", "javascript", "cypress", "jest", "junior"],
    features: ["2w ago", "Full Time", "Woldwide"],
  },
  {
    position: "Project Manager",
    business: "Shortly.inc",
    time: "",
    logo: shortly,
    id_class: ["senior", "python", "javascript", "cypress", "jest"],
    features: ["6w ago", "Full Time", "Woldwide"],
  },
  {
    position: "Backend Developer JR",
    business: "AirFilter",
    time: "",
    logo: airFilter,
    id_class: ["node", "python", "express", "PHP"],
    features: ["4d ago", "Full Time", "ARG only"],
  },
  {
    position: "Software Engineer JR",
    business: "PhotoSnapshot",
    time: "",
    logo: photoSnapshot,
    id_class: ["node", "express", "PHP", "javascript", "junior"],
    features: ["9w ago", "Full Time", "IRL only"],
  },
  {
    position: "Software Architect SR",
    business: "Account",
    time: "",
    logo: account,
    id_class: [
      "javascript",
      "python",
      "jest",
      "CI/CD",
      "kubernates",
      "jenkins",
    ],
    features: ["19w ago", "Full Time", "USA only"],
  },
];

export default data;
